# Enable multiple mega's at one time
# Allowed values: true, false - Default: false
multipleMegas = true

# Enable mega evolution only for battles
# Allowed values: true, false - Default: false
battleModeOnly = false

# Enables/Disables zMoves in game
# Allowed values: true, false - Default: true
zMoves = true

# Enables/Disables teralization in game
# Allowed values: true, false - Default: true
teralization = true

# Enables etermax eternus forme
# Allowed values: true, false - Default: true
etermaxForme = true

# Enables/Disables Dmaxing in game
# Allowed values: true, false - Default: true
dynamax = true

# Enables/Disables Mega in game
# Allowed values: true, false - Default: true
mega = true

# Allows you to dynamax anywhere you dont need to be near the dynamax area
# Allowed values: true, false - Default: false
dynamaxAnywhere = false

# Range around a power spot where Dynamax is allowed
# Allowed range: 0 ~ 10000 - Default: 20
powerSpotRange = 20

# By how many times should the pokemon size increase when g/dmaxing
# Allowed range: -10 ~ 10000 - Default: 4
dynamaxScaleFactor = 4

#  Enable/Disable loading of showdown files from the mod, 
# note this means once you load the game and the showdown changes have been affected you disable
# this it will stop overwriting it ever load, this is for people who want to edit showdown 
# but can't since mega showdown keeps overriding the files
# Allowed values: true, false - Default: true
showdownFilesLoading = true

# Allows you to have multiple primals
# Allowed values: true, false - Default: true
multiplePrimals = true

# Enable/Disable mega pokemons form reverting when battle starts
# Allowed values: true, false - Default: true
revertMegas = true

# Number of tera shards required to change tera type
# Allowed range: 1 ~ 50 - Default: 50
teraShardRequired = 50

# Terashard drop rate
# Allowed range: -1.0 ~ 100.0 - Default: 10.0
teraShardDropRate = 10.0

# Stellar tera shard drop rate
# Allowed range: -1.0 ~ 10.0 - Default: 1.0
stellarShardDropRate = 1.0

